Feature/api
Chirkovl/TaskManager pull request #12
Opened 2021-11-28 12:47 UTC by Chirkovl

2021-11-28 18:14 UTC, greybutton requested changes
настрой уже редактор, чтобы отступы везде были одинаковые пробелами. у тебя они постоянно пляшут между файлами

2021-11-28 18:14 UTC, greybutton commented on test/factories/tasks.rb
> +    assignee_id { create :user }
почему поменял?

2021-11-28 18:54 UTC, Chirkovl commented on test/factories/tasks.rb
> +    assignee_id { create :user }
> 
 Это в задании "Правим фабрики для тестов" . Могу я отрудокопить после мержа в девелоп - бренч? (Чтобы изменения нескольких уроков не попали в один пул-реквест. Или это уже настройки самого VS Code?)

2021-11-29 15:02 UTC, greybutton commented on test/factories/tasks.rb
> +    assignee_id { create :user }
давай здесь все изменения сделаем. Насчет настроек VS Code не знаю, выглядит как локальное что то у тебя делает разные отступы в файлах

2021-11-29 18:28 UTC, greybutton approved these changes

2021-12-06 15:24 UTC, merged