Feature/coverals1
Chirkovl/TaskManager pull request #20
Opened 2022-09-17 14:18 UTC by Chirkovl

2022-09-19 14:48 UTC, Chirkovl commented
Я не совсем понимаю как мне правильно назвать окружение, чтобы добавить COVERALLS_REPO_TOKEN. Пробовал разные варианты, но распознал лишь когда передал его в .coveralls.yml. А это не правильно и не по заданию.

2022-09-19 15:59 UTC, Chirkovl commented
Я не совсем понимаю как мне правильно назвать окружение, чтобы добавить COVERALLS_REPO_TOKEN. Пробовал разные варианты, но распознал лишь когда передал его в .coveralls.yml. А это не правильно и не по заданию.

2022-09-19 17:08 UTC, greybutton requested changes
попробуйте использовать https://github.com/marketplace/actions/coveralls-github-action

2022-09-19 17:08 UTC, greybutton commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/Chirkovl/TaskManager/badge.svg?branch=master)](https://coveralls.io/github/Chirkovl/TaskManager?branch=master)
на develop ветку лучше

2022-09-19 17:08 UTC, greybutton commented on test/test_helper.rb
> +  SimpleCov.formatter = SimpleCov::Formatter::HTMLFormatter
else не нужен, только в ci генерируем покрытие

2022-09-19 17:08 UTC, greybutton commented on test/test_helper.rb
> +SimpleCov.start
это лучше в иф добавить, что только в ci генерировать покрытие

2022-09-19 19:59 UTC, Chirkovl commented
> попробуйте использовать https://github.com/marketplace/actions/coveralls-github-action
На самом деле помогло именно использовать гем coveralls. На хероку лью? вроде бы они скоро триалы уберут

2022-09-20 05:40 UTC, greybutton approved these changes

2022-09-20 05:40 UTC, greybutton commented on test/test_helper.rb
> +SimpleCov.start
SimpleCov.start лучше все таки убрать в иф

2022-09-20 07:45 UTC, merged