Generate models
Chirkovl/TaskManager pull request #4
Opened 2021-11-05 18:28 UTC by Chirkovl

2021-11-06 19:15 UTC, Andrew8xx8 requested changes

2021-11-06 19:15 UTC, Andrew8xx8 commented on test/factories/users.rb
> +    email { 'MyString' }
Здесь и ниже, во всех фабриках, нужно использовать сгенерированные значения, вместо статически заданных, по примеру как было с `first_name`, `last_name`

2021-11-06 21:09 UTC, Chirkovl commented on test/factories/users.rb
> +    email { 'MyString' }
> Здесь и ниже, во всех фабриках, нужно использовать сгенерированные значения, вместо статически заданных, по примеру как было с `first_name`, `last_name`
Спасибо) В фабрике tasks, в соответствии с заданием, author_id и assignee_id оставляю статическими?

2021-11-07 14:50 UTC, moklidia requested changes

2021-11-07 14:50 UTC, moklidia commented on test/factories/tasks.rb
> +    assignee_id { 1 }
author_id и assignee_id должны ссылаться на соответствующие фабрики

2021-11-07 18:41 UTC, Chirkovl commented on test/factories/tasks.rb
> +    assignee_id { 1 }
> author_id и assignee_id должны ссылаться на соответствующие фабрики

```suggestion
    assignee_id { 1 [}](url)
```Разве в задании "Генерация моделей" не сказано, что эти два параметра должны остаться статичными, до следующего задания?

2021-11-07 18:42 UTC, Chirkovl commented on test/factories/tasks.rb
> +    assignee_id { 1 }
> author_id и assignee_id должны ссылаться на соответствующие фабрики

Разве в задании "Генерация моделей" не сказано, что эти два параметра должны остаться статичными, до следующего задания?

2021-11-08 06:41 UTC, moklidia commented on test/factories/tasks.rb
> +    assignee_id { 1 }
Окей, отправь задание заново на проверку

2021-11-09 13:49 UTC, merged