Add session
Chirkovl/TaskManager pull request #8
Opened 2021-11-16 14:28 UTC by Chirkovl

2021-11-16 20:22 UTC, greybutton requested changes
тесты проходят?

2021-11-16 20:22 UTC, greybutton commented on config/routes.rb
> +    resource :session, only: [:new, :create, :destroy]
почему добавил новую строку, а не добавил в шестую?

2021-11-17 04:44 UTC, Chirkovl commented on config/routes.rb
> +    resource :session, only: [:new, :create, :destroy]
Чисто мой косяк)

2021-11-17 04:45 UTC, Chirkovl commented on config/routes.rb
> +    resource :session, only: [:new, :create, :destroy]
На счёт тестов буду смотреть, но я так понимаю, что нет.

2021-11-17 16:56 UTC, greybutton approved these changes
после удаления  старых строк можешь мержить, не критично)

2021-11-17 16:56 UTC, greybutton commented on app/views/web/sessions/new.html.slim
>  p Find me in app/views/web/sessions/new.html.slim
это нужно удалить

2021-11-17 17:14 UTC, Chirkovl commented on app/views/web/sessions/new.html.slim
>  p Find me in app/views/web/sessions/new.html.slim
Понял, спасибо)

2021-11-17 17:18 UTC, merged